#! /bin/sh
set -euo pipefail

echo "Agregando dependencias de Linux"
apk add util-linux zip unzip nano flex bison e2fsprogs e2fsprogs-extra

echo "Agregando dependencias para compilar QT6"
apk add qt6-qtbase-dev qt6-qtdeclarative-dev qt6-qtshadertools-dev cmake ninja build-base

apk add git ninja perl python3 gperf \
    mesa-dev libxkbcommon-dev wayland-dev libinput-dev \
    freetype-dev harfbuzz-dev fontconfig-dev
