#!/bin/sh
set -euo pipefail

export SYS_ARCH=$(uname -m)
if [ "$SYS_ARCH" = 'aarch64' ] || [ "$SYS_ARCH" = 'arm64' ]; then
	SYS_ARCH='arm64'
else 
	SYS_ARCH='amd64'
fi


export ROOT_PATH=$( pwd )

export WOLFBEAR_VERSION="1.0"
export WOLFBEAR_REPO_CERT="$ROOT_PATH/certs/wolfbear-repo.pem"
export WOLFBEAR_REPO_WWW="/scratch/www/os.wolfbear.mx/public/"
export WOLFBEAR_SNAPSHOT_ZIP_FILE="$WOLFBEAR_VERSION.zip"

export VERSION_LINUX_KERNEL=6.15
export BUSY_BOX_VERSION=1.37.0
export QT_VERSION=6.9.1

export OUTPUT_PATH="$ROOT_PATH/output"
export KERNEL_PATH="$ROOT_PATH/kernel"

export LINUX_SOURCE_CODE_DIR="$OUTPUT_PATH/source-code/linux"

export LINUX_COMPILED_DIR="$OUTPUT_PATH/compiled/linux"
export LINUX_MODULES_COMPILED_DIR="$OUTPUT_PATH/compiled/linux-modules"

export LINUX_PATCHES_DIR="$KERNEL_PATH/patches"
export LINUX_CONFIGS_PATH="$KERNEL_PATH/config"
