#! /bin/sh
set -euo pipefail

WOLFBEAR_VERSION="1.0"
WOLFBEAR_ARCHES="aarch64 x86_64"

WOLFBEAR_PACKAGES="
apk-tools
shadow  
dhcpcd  
openresolv  
util-linux  
strace  
openssh  
grub-efi  
parted  
e2fsprogs  
e2fsprogs-extra  
dosfstools  
rsync  
nano  
libc-utils
"

ALPINE_MAIN_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/main"
ALPINE_COMMUNITY_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/community"

for WOLFBEAR_ARCH in $WOLFBEAR_ARCHES; do
	APK_OUTPUT_SNAPSHOTS="./output/snapshots/"$WOLFBEAR_VERSION"/"$WOLFBEAR_ARCH"/mirrors"

	echo "Limpiando mirrors anteriores en $APK_OUTPUT_SNAPSHOTS"
	rm -rf "$APK_OUTPUT_SNAPSHOTS"
	mkdir -p "$APK_OUTPUT_SNAPSHOTS"

	apk fetch \
        --no-cache \
        --cache-dir /dev/null \
        --arch "$WOLFBEAR_ARCH" \
        --repository "$ALPINE_MAIN_REPO" \
        --repository "$ALPINE_COMMUNITY_REPO" \
        --output "$APK_OUTPUT_SNAPSHOTS" \
        --recursive \
        $WOLFBEAR_PACKAGES

done
