#!/bin/sh
set -euo pipefail

source ./globals

echo "Iniciando descarga del kernel de linux '$LINUX_SOURCE_CODE_DIR'"

if [ ! -d "$LINUX_SOURCE_CODE_DIR" ] || [ -z "$(ls -A "$LINUX_SOURCE_CODE_DIR")" ]; then
	echo "Linux kernel sera descargado desde su repositorio oficial"
	git clone -b v$VERSION_LINUX_KERNEL --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $LINUX_SOURCE_CODE_DIR

	echo "Linux kernel se ha descargado exitosamente"
else 
	echo "No es necesario descargar Linux Kernel ya que fue encontrado en la carpeta de dependencias"
fi
