#!/bin/sh
set -euo pipefail

source ./globals

echo "Aplicando parches correspondientes a Linux Kernel"

if patch -d "$LINUX_SOURCE_CODE_DIR" --dry-run --forward -p1 < $LINUX_PATCHES_DIR/000-linux-uts-name.patch > /dev/null; then

 	echo "Se encontró que el parche 000-linux-uts-name.patch no ha sido aplicado"
	
	patch -d "$LINUX_SOURCE_CODE_DIR" -p1 < "$LINUX_PATCHES_DIR/000-linux-uts-name.patch"
	
	echo "Parche 000-linux-uts-name.patch aplicado"

else
	echo "El parche 000-linux-uts-name.patch ya estaba previamente aplicado"
fi

if patch -d "$LINUX_SOURCE_CODE_DIR" --dry-run --forward -p1 < $LINUX_PATCHES_DIR/001-linux-blk-iocost-c-unsigned-int-format.patch > /dev/null; then

	echo "Se encontró que el parche 001-linux-blk-iocost-c-unsigned-int-format.patch no ha sido aplicado"
	
	patch -d "$LINUX_SOURCE_CODE_DIR" -p1 < "$LINUX_PATCHES_DIR/001-linux-blk-iocost-c-unsigned-int-format.patch"

	echo "Parche 001-linux-blk-iocost-c-unsigned-int-format.patch aplicado"

else
	echo "El parche 001-linux-blk-iocost-c-unsigned-int-format.patch ya estaba previamente aplicado"
fi

echo "Se ha terminado el proceso de parcheo a Linux Kernel"