#!/bin/sh
set -euo pipefail

source ./globals

echo "Iniciando configuración del kernel de linux '$DEPENDENCY_LINUX_DIR'"
echo "Se compilará el kernel para la arquitectura '$SYS_ARCH'"

echo "Eliminando archivo de configuración si existe en '$DEPENDENCY_LINUX_DIR/.config'"
rm -f "$DEPENDENCY_LINUX_DIR"/.config

CONFIG_IN_PROJECT="$LINUX_CONFIGS_PATH/linux-config-$SYS_ARCH"
CONFIG_IN_LINUX_DIR="$DEPENDENCY_LINUX_DIR/.config"

echo "Copiando archivo de configuración desde '$CONFIG_IN_PROJECT' hasta '$CONFIG_IN_LINUX_DIR'" 1
cp $CONFIG_IN_PROJECT $CONFIG_IN_LINUX_DIR

log_message $SCRIPT_NAME "Archivo de configuración sincronizado exitosamente en '$DEPENDENCY_LINUX_DIR'"