#!/bin/sh
set -euo pipefail

source ./globals

echo "Iniciando configuración del kernel de linux '$LINUX_SOURCE_CODE_DIR'"
echo "Se compilará el kernel para la arquitectura '$SYS_ARCH'"

echo "Eliminando archivo de configuración si existe en '$LINUX_SOURCE_CODE_DIR/.config'"
rm -f "$LINUX_SOURCE_CODE_DIR"/.config

CONFIG_IN_PROJECT="$LINUX_CONFIGS_PATH/linux-config-$SYS_ARCH"
CONFIG_IN_LINUX_DIR="$LINUX_SOURCE_CODE_DIR/.config"

echo "Copiando archivo de configuración desde '$CONFIG_IN_PROJECT' hasta '$CONFIG_IN_LINUX_DIR'"
cp $CONFIG_IN_PROJECT $CONFIG_IN_LINUX_DIR

echo "Archivo de configuración sincronizado exitosamente en '$LINUX_SOURCE_CODE_DIR'"