#!/bin/sh
set -euo pipefail

./globals

echo "Iniciando descarga del kernel de linux '$DEPENDENCY_LINUX_DIR'"

if [ ! -d "$DEPENDENCY_LINUX_DIR" ] || [ -z "$(ls -A "$DEPENDENCY_LINUX_DIR")" ]; then
	echo "Linux kernel sera descargado desde su repositorio oficial"
	git clone -b v$VERSION_LINUX_KERNEL --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $DEPENDENCY_LINUX_DIR

	echo "Linux kernel se ha descargado exitosamente"
else 
	echo "No es necesario descargar Linux Kernel ya que fue encontrado en la carpeta de dependencias"
fi
