#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Aplicando parches correspondientes a Linux Kernel"
cd $DEPENDENCY_LINUX_DIR

if patch --dry-run --forward -p1 < $PATCHES_DIR/000-linux-uts-name.patch > /dev/null; then
 	debug_message $SCRIPT_NAME "Se encontró que el parche 000-linux-uts-name.patch no ha sido aplicado"
	patch -p1 < $PATCHES_DIR/000-linux-uts-name.patch
	debug_message $SCRIPT_NAME "Parche 000-linux-uts-name.patch aplicado"
else
	debug_message $SCRIPT_NAME "El parche 000-linux-uts-name.patch ya estaba previamente aplicado"
fi

if patch --dry-run --forward -p1 < $PATCHES_DIR/001-linux-blk-iocost-c-unsigned-int-format.patch > /dev/null; then
	debug_message $SCRIPT_NAME "Se encontró que el parche 001-linux-blk-iocost-c-unsigned-int-format.patch no ha sido aplicado"
	patch -p1 < $PATCHES_DIR/001-linux-blk-iocost-c-unsigned-int-format.patch
	debug_message $SCRIPT_NAME "Parche 001-linux-blk-iocost-c-unsigned-int-format.patch aplicado"
else
	debug_message $SCRIPT_NAME "El parche 001-linux-blk-iocost-c-unsigned-int-format.patch ya estaba previamente aplicado"
fi

log_message $SCRIPT_NAME "Se ha terminado el proceso de parcheo a Linux Kernel"