#!/bin/sh
set -euo pipefail

source ./globals

echo "Iniciando compilación de Linux Kernel"

echo "Accediendo al directorio '$LINUX_SOURCE_CODE_DIR'"
cd $LINUX_SOURCE_CODE_DIR

echo "Compilando kernel"

make -j$(nproc)

echo "Compilación realizada exitosamente"