#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando configuración del kernel de linux '$DEPENDENCY_LINUX_DIR'"
debug_message $SCRIPT_NAME "Se compilará el kernel para la arquitectura '$SYS_ARCH'"

debug_message $SCRIPT_NAME "Eliminando archivo de configuración si existe en '$DEPENDENCY_LINUX_DIR/.config'"
rm -f "$DEPENDENCY_LINUX_DIR"/.config

CONFIG_IN_PROJECT="$CONFIG_FILES_DIR/linux-config-$SYS_ARCH"
CONFIG_IN_LINUX_DIR="$DEPENDENCY_LINUX_DIR/.config"

debug_message $SCRIPT_NAME "Copiando archivo de configuración desde '$CONFIG_IN_PROJECT' hasta '$CONFIG_IN_LINUX_DIR'" 1
cp $CONFIG_IN_PROJECT $CONFIG_IN_LINUX_DIR

log_message $SCRIPT_NAME "Archivo de configuración sincronizado exitosamente en '$DEPENDENCY_LINUX_DIR'"