#!/bin/sh
set -euo pipefail

source ./globals

cd "$ROOT_PATH"

echo "Iniciando compilación de Módulos Linux Kernel"

echo "Accediendo al directorio '$LINUX_SOURCE_CODE_DIR'"
cd $LINUX_SOURCE_CODE_DIR/

echo "Solicitando compilación de módulos"
make -j$(nproc) modules

echo "Limpiando módulos anteriores en '$LINUX_MODULES_COMPILED_DIR'"

rm -rf $LINUX_MODULES_COMPILED_DIR
mkdir -p $LINUX_MODULES_COMPILED_DIR

echo "Compilando módulos en '$LINUX_MODULES_COMPILED_DIR'"
make -j$(nproc) modules_install INSTALL_MOD_PATH="$LINUX_MODULES_COMPILED_DIR"

echo "Compilación realizada exitosamente"

cd "$DEPENDENCIES_LINUX_MODULES_DIR"
zip -r linux-modules.zip .

cd "$ROOT_PATH"