#!/bin/sh
set -euo pipefail

source ./globals

echo "Moviendo compilado de imágenes de Linux Kernel a '$LINUX_COMPILED_DIR'"

if [ "$SYS_ARCH" = "arm64" ]; then
  SRC_ARCH=arm64
  IMG=Image
elif [ "$SYS_ARCH" = "amd64" ] || [ "$SYS_ARCH" = "x86_64" ]; then
  SRC_ARCH=x86
  IMG=bzImage
else
  echo "Arquitectura desconocida '$SYS_ARCH'"
  exit 1
fi

IMAGE_DIR="$LINUX_SOURCE_CODE_DIR/arch/$SRC_ARCH/boot/$IMG"

rm -rf "$LINUX_COMPILED_DIR"
mkdir -p "$LINUX_COMPILED_DIR"

echo "Se moverá el archivo '$IMAGE_DIR' hacia el directorio '$LINUX_COMPILED_DIR'"
mv $IMAGE_DIR "$LINUX_COMPILED_DIR"

echo "Se han movido los archivos compilados de Linux Kernel exitosamente"