#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "El usuario solicitó abrir el menú de configuración de Linux Kernel para cambiar la configuración"
debug_message $SCRIPT_NAME "Abriendo directorio '$DEPENDENCY_LINUX_DIR'"

cd $DEPENDENCY_LINUX_DIR

debug_message $SCRIPT_NAME "Solicitando 'make menuconfig'"
new_line

make menuconfig

PROJECT_CONFIG="$WOLFBEAR_OS_DIR/config/linux-config-$SYS_ARCH"
DEPENDENCY_CONFIG="$DEPENDENCY_LINUX_DIR/.config"

debug_message $SCRIPT_NAME "Sincronizando cambios hechos desde '$DEPENDENCY_CONFIG' hasta '$PROJECT_CONFIG'"

rm -f $PROJECT_CONFIG
cp $DEPENDENCY_CONFIG $PROJECT_CONFIG

log_message $SCRIPT_NAME "Archivo de configuración sincronizado exitosamente en '$PROJECT_CONFIG'"