#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "El usuario solicitó limpiar la compilación de Linx Kernel"
log_message $SCRIPT_NAME "Esto solo se recomienda si es la primera compilación o hiciste cambios significativos a Linux Kernel"

cd $DEPENDENCY_LINUX_DIR

debug_message $SCRIPT_NAME "Solicitando 'make clean'"
make clean

log_message $SCRIPT_NAME "Limpieza realizada exitosamente"