#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando compilación de Módulos Linux Kernel"

debug_message $SCRIPT_NAME "Accediendo al directorio '$DEPENDENCY_LINUX_DIR'"
cd $DEPENDENCY_LINUX_DIR

debug_message $SCRIPT_NAME "Solicitando compilación de módulos"
make -j$(nproc) modules

debug_message $SCRIPT_NAME "Limpiando módulos anteriores en '$DEPENDENCIES_LINUX_MODULES_DIR'"

rm -rf $DEPENDENCIES_LINUX_MODULES_DIR
mkdir -p $DEPENDENCIES_LINUX_MODULES_DIR

debug_message $SCRIPT_NAME "Compilando módulos en '$DEPENDENCIES_LINUX_MODULES_DIR'"
make -j$(nproc) modules_install INSTALL_MOD_PATH=$DEPENDENCIES_LINUX_MODULES_DIR

log_message $SCRIPT_NAME "Compilación realizada exitosamente"