#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Moviendo compilado de imágenes de Linux Kernel a '$TARGET_DIR'"

if [ "$SYS_ARCH" = "arm64" ]; then
  SRC_ARCH=arm64
  IMG=Image
elif [ "$SYS_ARCH" = "amd64" ] || [ "$SYS_ARCH" = "x86_64" ]; then
  SRC_ARCH=x86
  IMG=bzImage
else
  error_message $SCRIPT_NAME "Arquitectura desconocida '$SYS_ARCH'"
  exit 1
fi

IMAGE_DIR="$DEPENDENCY_LINUX_DIR/arch/$SRC_ARCH/boot/$IMG"

debug_message $SCRIPT_NAME "Se moverá el archivo '$IMAGE_DIR' hacia el directorio '$TARGET_DIR'"
mv $IMAGE_DIR $TARGET_DIR

log_message $SCRIPT_NAME "Se han movido los archivos compilados de Linux Kernel exitosamente"