#! /bin/sh

source ./globals

echo "Limpiando  para $WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION"

ssh -i "$WOLFBEAR_REPO_CERT" -t wolfbear@wolfbear.mx <<'ENDSSH'
    rm -rf "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION"
    
    mkdir -p "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/aarch64/apk"
    mkdir -p "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/aarch64/kernel"
    mkdir -p "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/aarch64/platforms"

    mkdir -p "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/x86_64/apk"
    mkdir -p "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/x86_64/kernel"
    mkdir -p "$WOLFBEAR_REPO_WWW/$WOLFBEAR_VERSION/x86_64/platforms"

ENDSSH