#! /bin/sh

source ./globals

cd $ROOT_PATH

scp -i "$WOLFBEAR_REPO_CERT" "$OUTPUT_PATH/snapshots/$WOLFBEAR_SNAPSHOT_ZIP_FILE" wolfbear@wolfbear.mx:"$WOLFBEAR_REPO_WWW"

ssh -i "$WOLFBEAR_REPO_CERT" -t wolfbear@wolfbear.mx <<'ENDSSH'
    cd "$WOLFBEAR_REPO_WWW
    unzip "$WOLFBEAR_SNAPSHOT_ZIP_FILE"
ENDSSH