#! /bin/sh
set -euo pipefail

source ./globals

WOLFBEAR_ARCHES="aarch64 x86_64"

WOLFBEAR_PACKAGES="
apk-tools
shadow  
dhcpcd  
openresolv  
util-linux  
strace  
openssh  
grub-efi  
parted  
e2fsprogs  
e2fsprogs-extra  
dosfstools  
rsync  
nano  
libc-utils
"

ALPINE_MAIN_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/main"
ALPINE_COMMUNITY_REPO="https://dl-cdn.alpinelinux.org/alpine/v3.22/community"

for WOLFBEAR_ARCH in $WOLFBEAR_ARCHES; do
    ARCH_OUTPUTS=$OUTPUT_PATH"/snapshots/$WOLFBEAR_VERSION/$WOLFBEAR_ARCH/"
    APK_OUTPUT_SNAPSHOTS="$ARCH_OUTPUTS/apk"

	echo "Limpiando mirrors anteriores en $APK_OUTPUT_SNAPSHOTS"
	rm -rf "$APK_OUTPUT_SNAPSHOTS"
	mkdir -p "$APK_OUTPUT_SNAPSHOTS"

    echo "Descargando dependencias APK"
	apk fetch \
        --no-cache \
        --cache-dir /dev/null \
        --arch "$WOLFBEAR_ARCH" \
        --repository "$ALPINE_MAIN_REPO" \
        --repository "$ALPINE_COMMUNITY_REPO" \
        --repositories-file /dev/null \
        --allow-untrusted \
        --output "$APK_OUTPUT_SNAPSHOTS" \
        --recursive \
        $WOLFBEAR_PACKAGES

    echo "Generando indices"
    (
        cd "$APK_OUTPUT_SNAPSHOTS"
        rm -f APKINDEX.tar.gz
        apk index -o APKINDEX.tar.gz
        ls -lh APKINDEX.tar.gz
    )

done

cd "$OUTPUT_PATH/snapshots/"

rm -f "$WOLFBEAR_SNAPSHOT_ZIP_FILE"
zip -r "$WOLFBEAR_SNAPSHOT_ZIP_FILE" "$WOLFBEAR_VERSION/"