#!/bin/sh
set -euo pipefail

source ./globals

cd $ROOT_PATH

echo "Iniciando descarga de Busybox '$BUSYBOX_SOURCE_CODE_DIR' en su versión '$BUSY_BOX_VERSION'"
sleep 0.2

echo "Abriendo directorio de dependencias '$BUSYBOX_SOURCE_CODE_DIR'"
sleep 0.2

cd $SOURCE_CODE_DIR

if [ ! -d "$BUSYBOX_SOURCE_CODE_DIR" ] || [ -z "$(ls -A "$BUSYBOX_SOURCE_CODE_DIR")" ]; then
	echo "Busybox será descargado desde su repositorio oficial"
    sleep 0.2

	rm -f "$SOURCE_CODE_DIR/busybox-$BUSY_BOX_VERSION.tar.bz2"

	wget https://busybox.net/downloads/busybox-$BUSY_BOX_VERSION.tar.bz2

	echo "Descomprimiendo Busybox"
    sleep 0.2

	tar -xjf "busybox-$BUSY_BOX_VERSION.tar.bz2"
    mv "busybox-$BUSY_BOX_VERSION" busybox

    rm "busybox-$BUSY_BOX_VERSION.tar.bz2"

	echo "Busybox ha sido descargado exitosamente"
    sleep 0.2
else 
	echo "No es necesario descargar Busybox ya que fue encontrado en la carpeta de dependencias"
    sleep 0.2
fi

echo "El script para descargar Busybox ha finalizado"
sleep 0.2