#! /bin/sh

source ./globals

cd "$BUSYBOX_SOURCE_CODE_DIR"

if patch --dry-run --forward -p1 < $BUSYBOX_PATCHES_DIR/busybox-dialog-ncurses-fix.patch > /dev/null; then
    echo "Aplicando parches para ncurses fix en Alpine"
    patch -p1 < $BUSYBOX_PATCHES_DIR/busybox-dialog-ncurses-fix.patch
fi